### ISSUE TITLE
modifications during migration

### ISSUE THREAD

**Issue by travi** [joebowbeer/regsync#10]
first, thank you for making this tool available. it has been very helpful during a migration between artifactory instances. the ability to only migrate missing versions has been a big help since the migration has been spread over a bit of time.

i'm curious, though, if you've considered having an ability to make any modifications to each version while transferring them. i've been investigating github packages, and it is a bit more strict in some areas than artifactory was. in particular, they require the `repository` details to be populated when the package name does not match the repository name. as much as i dont like the idea of making any modifications to existing versions, we need that additional metadata to be included in order to successfully republish to github packages.

would this be functionality that you would see as valuable in this project?

**Comment by joebowbeer** [comment]
Can you provide more specifics?

There is already a `prepareManifest` function that makes some mods. Perhaps these mods **_are_** the source of your problems?

**Comment by travi** [comment]
sorry, i should have clarified. i have not attempted to migrate a package to github packages using this tool yet, but ran into publish failures (404s when publishing) with manual PoCs when the `repository` details were missing from the `package.json` since GitHub was unable to associate the package with a source repository.

here is some of the github documentation about specifying the `repository` details for a monorepo context: https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-npm-for-use-with-github-packages#publishing-multiple-packages-to-the-same-repository. while not fully required on the github side, [defining a `directory` within the repository](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository) is also possible and github honors that detail, when present. we would likely want to include that if we were to apply the basic update.

i had already glanced at the `prepareManifest` implementation, but somehow overlooked the line about updating the `repository` details: https://github.com/joebowbeer/regsync/blob/bd80db61a49e3d38f45723f67c5f7b603acb4a6f/src/util.ts#L79

perhaps this particular need is already solved by that. do i understand correctly that the `repository` details will automatically be applied to all transferred versions as long as it is present on the most recent version (i have already added the details to our more recent versions)? if so, i'm happy to close this issue. i wont be able to confirm right away, but could always reopen if i happen to find that to not solve our need.

**Comment by joebowbeer** [comment]
I added this function to overcome issues migrating to GitHub package manager.

**Comment by travi** [comment]
perfect. i expect that we're covered then. sorry for the noise.

**Comment by travi** [comment]
thought i would just circle back quickly to confirm that syncing to the github registry did work flawlessly. thanks a ton!
