### ISSUE TITLE
throw new Error('EINTEGRITY')

### ISSUE THREAD

**Issue by DeoLeung** [joebowbeer/regsync#13]
Thank you for the great tool

I'm migrating from verdaccio to nexus3 registry, all packages except one throws exception:
```bash
scope undefined
Source versions [
  '1.2.0',     '1.2.1',
  '1.2.2',     '1.2.3',
  '1.2.4',     '1.3.0',
  '1.1.6',     '1.2.0-mdt',
  '1.2.2-mdt'
]
Target versions []
Missing versions [
  '1.2.0',     '1.2.1',
  '1.2.2',     '1.2.3',
  '1.2.4',     '1.3.0',
  '1.1.6',     '1.2.0-mdt',
  '1.2.2-mdt'
]
Reading packages1@1.2.0 from https://source.com
Dist {
  shasum: 'da47a1f6978788df23cfbf04fc9caf03909237b8',
  tarball: 'https://souces.com/packages1/-/packages1-1.2.0.tgz'
}
/regsync/dist/util.js:82
    throw new Error('EINTEGRITY');
          ^

Error: EINTEGRITY
    at fetchTarball (/regsync/dist/util.js:82:11)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Object.sync (/regsync/dist/index.js:39:21)
```
not sure where to check

**Comment by joebowbeer** [comment]
The exception is thrown from my code:

https://github.com/joebowbeer/regsync/blob/master/src/util.ts#L65

In your case, it indicates that the shasum computed from the tarball doesn't match the value in the manifest. (I notice that in this case the manifest includes `shasum` but not `integrity`.)

Possible causes:
* tarball download was truncated (or corrupted)
* shasum stored in manifest does not match tarball

Try downloading the tarball to see if it is valid.

It looks like there have been some issues with shasum on verdaccio. For example, there was a bug that if the same version was published twice, it would update the shasum but not the tarball.

https://github.com/verdaccio/verdaccio/search?q=eintegrity&type=issues
https://github.com/verdaccio/verdaccio/search?q=shasum+eintegrity&type=issues
