### ISSUE TITLE
Error: 400 Bad Request - failed to stream package from json

### ISSUE THREAD

**Issue by bvellek** [joebowbeer/regsync#4]
Thank you for spending your time to create this package! I was trying to run this locally to migrate from npm private package registry over to a github private package registry, but I run into the following error:

```
Error: 400 Bad Request - PUT https://npm.pkg.github.com/@ORGINZATION%2fREPO_NAME - failed to stream package from json: parsing NPM metadata: json: cannot unmarshal number into Go struct field NpmVersionInfo.dist of type string
    at res.buffer.catch.then.body (/Users/benvellek/Desktop/repos/npm-github/node_modules/npm-registry-fetch/check-response.js:104:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12094) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

I have no problems when completing this as a dry run, but run into this issue whenever I try to run as dry run false. Any ideas?

Let me know if I can provide any other helpful info. Thanks!

**Comment by joebowbeerxealth** [comment]
I'm glad to see someone else using this! I used it to migrate from a private Nexus repo to private repos on GitHub. It looks like GPR is expecting a string but is getting a number. To be continued...

**Comment by joebowbeer** [comment]
I'm glad to see someone else using this! I used it to migrate from a private Nexus repo to private repos on GitHub. It looks like GPR is expecting a string but is getting a number. To be continued...

**Comment by joebowbeer** [comment]
The failure happens in the last step: publish.

At least, I should add an exception handler for the publish step to log and continue.

To help diagnose what the problem is, you can try looking at the metadata in your private repo. The dist fields in particular. See if any dist keys or fields are numbers instead of strings.

`npm view @scope/reponame`

`npx pacote packument @scope/reponame | jq`

**Comment by bvellek** [comment]
Thanks for the quick responses here!

I am seeing a different structure based on what version of my package I pull. The first version that is failing has `fileCount` and `unpackedSize` metadata keys in the `dist` which are numbers.

Previous versions only had `shasum` and `tarball`.

**Comment by joebowbeer** [comment]
I will report the issue to GitHub and also try to workaround by converting dist values to string (or removing non-string fields). I'm not sure which is more correct.

**Comment by joebowbeer** [comment]
Manifest fields `fileCount` and `unpackedSize` are documented here:
https://www.npmjs.com/package/pacote#manifests

**Comment by joebowbeer** [comment]
Should be fixed in `@joebowbeer/regsync@1.1.3`

**Comment by bvellek** [comment]
Hey @joebowbeer thanks so much for the quick help here! That seems to have done the trick!

**Comment by joebowbeer** [comment]
GitHub Developer Support informs me that the bug is now fixed, so I removed the workaround in `@joebowbeer/regsync@1.2.0`
